spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: vets-service
          uri: http://vets-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2


grpc:
  client:
    visits-grpc-server:
      address: 'discovery:///visits-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    customers-grpc-server:
      address: 'discovery:///customers-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
